### ISSUE TITLE
Please add support for ed25519 keys

### ISSUE THREAD

**Issue by nirgal** [xelerance/sshfp#7]
Hi

Modern ssh installation will generate a /etc/ssh/ssh_host_ed25519_key.pub
ssh-keyscan will return something like:
localhost ssh-ed25519 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

Iana assigned (temporarily) type 4 to this algorithm
https://www.iana.org/assignments/dns-sshfp-rr-parameters/dns-sshfp-rr-parameters.xml

It would be nice if sshfp could generate the appropriate SSHFP records.

**Comment by xelerance** [comment]
I pulled your changes, is that enough ?

**Comment by nirgal** [comment]
Yes, that fixes it.

I wonder if you want to keep maintaining sshfp, because there is a good fork there:
https://github.com/letoams/hash-slinger

Maybe you should say in the README to look there...

Closing the issue anyways

**Comment by nirgal** [comment]
Any plan to release a new version with last changes?

Last version "1.2.2" is 4 years old:
https://github.com/xelerance/sshfp/releases

**Comment by nirgal** [comment]
Ping?
